[package]
name = "magnetfinder"
version = "0.4.0"
authors = ["bleusakura", "crazyoptimist"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://github.com/crazyoptimist/magnetfinder"
repository = "https://github.com/crazyoptimist/magnetfinder"
description = "CLI Application for Finding Torrent Magnets on the Internet"
keywords = ["cli", "torrent"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "2.2.0", features = ["json", "socks-proxy"] }
scraper = "0.12.0"
comfy-table = "4.1.1"
config = "0.11.0"
directories = "3.0.2"
clap = "2.33.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
